version: '2'
services:
  usermanagementservice-postgresql:
    image: postgres:12.1
    # volumes:
    #     - ~/volumes/jhipster/UserManagementService/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=UserManagementService
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
